#!/bin/bash
# Fetch the AI-AUTHORED procedural corpus for the authorship run
# (docs/AI-AUTHORED-VALIDATION.md). Raw data stays out of git
# (validation/data/ is .gitignored); this script makes the run reproducible.
#
# Why this corpus: "human-written corpus; AI-authored operational text still
# unmeasured" has been the program's oldest open flag since the prometheus
# run (docs/PROMETHEUS-RUNBOOK-VALIDATION.md, flag 3), repeated in every
# fresh-corpus run since. This closes it with a corpus that is AI-authored BY
# CONSTRUCTION: Cosmopedia (HuggingFaceTB/cosmopedia), a fully synthetic
# dataset generated by Mixtral-8x7B-Instruct — the `wikihow` config is
# procedural how-to documents (steps, cautions, materials), the closest
# machine-authored analogue of the human procedural registers already
# measured (runbooks, how-to plans). The authorship label is the dataset's
# own construction, not an annotator's opinion.
#
# Population: the first 600 rows of config `wikihow`, split `train`, fetched
# via the datasets-server rows API — the same fetch path as the R1.x
# relational corpora (fetch-corpora.sh). Reproducibility class: date-bounded
# (the API serves the dataset's current revision; dataset/config/split/offsets
# recorded here). Fetch date for the recorded run: 2026-07-17.
#
# Reproduce: bash fetch-ai-authored-corpus.sh, then node ai-authored-validation.js
set -e

OUT="$(dirname "$0")/data/ai-authored"
mkdir -p "$OUT"
cd "$OUT"

for off in 0 100 200 300 400 500; do
  curl -sS --max-time 120 "https://datasets-server.huggingface.co/rows?dataset=HuggingFaceTB%2Fcosmopedia&config=wikihow&split=train&offset=$off&length=100" -o cw_$off.json
  sleep 0.3
done

echo "AI-authored corpus fetched into $(pwd)"
echo "batches: $(ls cw_*.json | wc -l) x 100 rows (cosmopedia wikihow, train)"
